---
# Source: calendar/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar
  labels:
    helm.sh/chart: calendar-0.1.0
    app.kubernetes.io/name: calendar
    app.kubernetes.io/instance: calendar
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: calendar
      app.kubernetes.io/instance: calendar
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calendar
        app.kubernetes.io/instance: calendar
    spec:
      securityContext:
        {}
      containers:
        - name: calendar
          securityContext:
            {}
          image: "datadog/opentelemetry-examples:calendar-java-20240916"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /calendar
              port: http
          readinessProbe:
            httpGet:
              path: /calendar
              port: http
          env:
            - name: OTEL_SERVICE_NAME
              value: calendar
            - name: OTEL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OTEL_K8S_POD_UID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: HOST_IP
              valueFrom:
               fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: OTLP_GRPC_PORT
              value: "4317"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://$(HOST_IP):$(OTLP_GRPC_PORT)'
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: 'grpc'
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: >-
                service.name=$(OTEL_SERVICE_NAME),
                service.version=1.0.0,
                service.instance.id=$(OTEL_K8S_POD_UID),
                k8s.namespace.name=$(OTEL_K8S_NAMESPACE),
                k8s.node.name=$(OTEL_K8S_NODE_NAME),
                k8s.pod.name=$(OTEL_K8S_POD_NAME),
                k8s.pod.ip=$(POD_IP),
                k8s.container.name=calendar,
                host.name=$(OTEL_K8S_NODE_NAME),
                deployment.environment=$(OTEL_K8S_NAMESPACE)
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500M
