---
# Source: datadog/templates/install_info-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-datadog-installinfo
  namespace: demo
  labels:
    helm.sh/chart: 'datadog-3.110.14'
    app.kubernetes.io/name: "otel-agent-datadog"
    app.kubernetes.io/instance: "otel-agent"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
  annotations:
    checksum/install_info: 0f7bb4eade598e93d57b0697280367242e5c206a6a42fb6e6125ea5031e0ba60
data:
  install_info: |
    ---
    install_method:
      tool: helm
      tool_version: Helm
      installer_version: datadog-3.110.14
