---
# Source: datadog/templates/kpi-telemetry-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-datadog-kpi-telemetry-configmap
  namespace: demo
  labels:
    helm.sh/chart: 'datadog-3.110.14'
    app.kubernetes.io/name: "otel-agent-datadog"
    app.kubernetes.io/instance: "otel-agent"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
data:
  install_type: k8s_manual
  install_id: "44f392d4-fc80-4e0e-a51a-08358fcfce43"
  install_time: "1745834113"
