---
# Source: datadog/templates/secret-cluster-agent-token.yaml
apiVersion: v1
kind: Secret
metadata:
  name: otel-agent-datadog-cluster-agent
  namespace: demo
  labels:
    helm.sh/chart: 'datadog-3.88.1'
    app.kubernetes.io/name: "otel-agent-datadog"
    app.kubernetes.io/instance: "otel-agent"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
type: Opaque
data:
  token: "VHZUOG1jaDNYVkEwa2lPeGdET3d3WlVBWklZVkZheHk="
