receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-agent"
          scrape_interval: 10s
          static_configs:
            - targets:
                - 0.0.0.0:8888
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    exclude:
      - /var/log/pods/*/otel-agent/*.log
      - /var/log/pods/*/agent/*.log
      - /var/log/pods/*/trace-agent/*.log
      - /var/log/pods/*/process-agent/*.log
    include:
      - /var/log/pods/*/*/*.log
    include_file_name: false
    include_file_path: true
    operators:
      - id: container-parser
        max_log_size: 102400
        type: container
    retry_on_failure:
      enabled: true
    start_at: end
exporters:
  debug:
    verbosity: detailed
  datadog:
    api:
      key: ${env:DD_API_KEY}
      site: ${env:DD_SITE}
processors:
  infraattributes:
    cardinality: 2
  batch:
    timeout: 10s
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
connectors:
  datadog/connector:
    traces:
service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, infraattributes, batch]
      exporters: [debug, datadog, datadog/connector]
    metrics:
      receivers: [otlp, datadog/connector, prometheus]
      processors: [memory_limiter, infraattributes, batch]
      exporters: [debug, datadog]
    logs:
      receivers: [filelog, otlp]
      processors: [memory_limiter, infraattributes, batch]
      exporters: [debug, datadog]
