agents:
  image:
    repository: public.ecr.aws/datadog/agent
    tag: 7.64.3-ot-beta
    pullPolicy: Always
    doNotCheckTag: true

datadog:
  site: datadoghq.com
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  logLevel: info

  otelCollector:
    enabled: true
    ports:
      - containerPort: "4317"
        hostPort: "4317"
        name: otel-grpc
      - containerPort: "4318"
        hostPort: "4318"
        name: otel-http
    logs:
      enabled: true

  apm:
    portEnabled: true
    peer_tags_aggregation: true
    compute_stats_by_span_kind: true
    peer_service_aggregation: true
  orchestratorExplorer:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  networkMonitoring:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    autoMultiLineDetection: false
  containerExcludeLogs: "name:.*"
  containerIncludeLogs: "name:ddlogger"
  kubelet:
    tlsVerify: false
  podLabelsAsTags:
    app: kube_app
    release: helm_release

  env:
    - name: DD_ENV
      value: demo
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
