agents:
  image:
    repository: public.ecr.aws/datadog/agent
    tag: 7.61.0-ot-beta
    pullPolicy: Always
    doNotCheckTag: true

  volumeMounts:
    - name: logpodpath
      mountPath: /var/log/pods
      mountPropagation: None
      readOnly: true
    - name: logscontainerspath
      mountPath: /var/log/containers
      mountPropagation: None
      readOnly: true
    - name: logdockercontainerpath
      mountPath: /var/lib/docker/containers
      mountPropagation: None
      readOnly: true

datadog:
  site: datadoghq.com
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  logLevel: info

  clusterName: krlv-opw

  otelCollector:
    enabled: true
    ports:
      - containerPort: "4317"
        hostPort: "4317"
        name: otel-grpc
      - containerPort: "4318"
        hostPort: "4318"
        name: otel-http

  apm:
    portEnabled: true
    peer_tags_aggregation: true
    compute_stats_by_span_kind: true
    peer_service_aggregation: true
  orchestratorExplorer:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  networkMonitoring:
    enabled: true
  logs:
    enabled: false
  kubelet:
    tlsVerify: false
  podLabelsAsTags:
    app: kube_app
    release: helm_release

  env:
    - name: DD_ENV
      value: staging
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName