---
# Source: opentelemetry-collector/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector-gw-opentelemetry-collector
  namespace: demo-zapus
  labels:
    helm.sh/chart: opentelemetry-collector-0.108.0
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: collector-gw
    app.kubernetes.io/version: "0.111.0"
    app.kubernetes.io/managed-by: Helm
