---
# Source: datadog/templates/cluster-agent-rbac.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  labels:
    app: "agent-hippo-datadog"
    chart: "datadog-3.77.0"
    heritage: "Helm"
    release: "agent-hippo"
    helm.sh/chart: 'datadog-3.77.0'
    app.kubernetes.io/name: "agent-hippo-datadog"
    app.kubernetes.io/instance: "agent-hippo"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
  name: agent-hippo-datadog-cluster-agent
  namespace: calendar-hippo
---
# Source: datadog/templates/cluster-agent-rbac.yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRole
metadata:
  labels:
    helm.sh/chart: 'datadog-3.77.0'
    app.kubernetes.io/name: "agent-hippo-datadog"
    app.kubernetes.io/instance: "agent-hippo"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
  name: agent-hippo-datadog-cluster-agent
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - namespaces
  - componentstatuses
  - limitranges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups: ["quota.openshift.io"]
  resources:
  - clusterresourcequotas
  verbs:
  - get
  - list
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - agent-hippo-datadogtoken  # Kubernetes event collection state
  - datadogtoken  # Kept for backward compatibility with agent <7.37.0
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - agent-hippo-datadog-leader-election  # Leader election token
  - datadog-leader-election  # Kept for backward compatibility with agent <7.37.0
  verbs:
  - get
  - update
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  resourceNames:
  - agent-hippo-datadog-leader-election  # Leader election token
  verbs:
  - get
  - update
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
- apiGroups:  # To create the leader election token and hpa events
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - create
- nonResourceURLs:
  - "/version"
  - "/healthz"
  verbs:
  - get
- apiGroups:  # to get the kube-system namespace UID and generate a cluster ID
  - ""
  resources:
  - namespaces
  resourceNames:
  - "kube-system"
  verbs:
  - get
- apiGroups:  # To create the cluster-id configmap
  - ""
  resources:
  - configmaps
  resourceNames:
  - "datadog-cluster-id"
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  - persistentvolumeclaims
  - serviceaccounts
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  - jobs
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "storage.k8s.io"
  resources:
  - storageclasses
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers
  verbs:
  - list
  - get
  - watch
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - list
    - get
    - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  resourceNames:
    - "datadog-webhook"
  verbs: ["get", "list", "watch", "update"]
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "replicasets", "deployments", "daemonsets"]
  verbs: ["get"]
- apiGroups:
  - "security.openshift.io"
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - agent-hippo-datadog-cluster-agent
  - hostnetwork
---
# Source: datadog/templates/cluster-agent-rbac.yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: 'datadog-3.77.0'
    app.kubernetes.io/name: "agent-hippo-datadog"
    app.kubernetes.io/instance: "agent-hippo"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
  name: agent-hippo-datadog-cluster-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-hippo-datadog-cluster-agent
subjects:
  - kind: ServiceAccount
    name: agent-hippo-datadog-cluster-agent
    namespace: calendar-hippo
---
# Source: datadog/templates/cluster-agent-rbac.yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: Role
metadata:
  labels:
    helm.sh/chart: 'datadog-3.77.0'
    app.kubernetes.io/name: "agent-hippo-datadog"
    app.kubernetes.io/instance: "agent-hippo"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
  name: agent-hippo-datadog-cluster-agent-main
  namespace: calendar-hippo
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "create"]
---
# Source: datadog/templates/cluster-agent-rbac.yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: RoleBinding
metadata:
  labels:
    helm.sh/chart: 'datadog-3.77.0'
    app.kubernetes.io/name: "agent-hippo-datadog"
    app.kubernetes.io/instance: "agent-hippo"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
  name: "agent-hippo-datadog-cluster-agent-main"
  namespace: calendar-hippo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-hippo-datadog-cluster-agent-main
subjects:
  - kind: ServiceAccount
    name: agent-hippo-datadog-cluster-agent
    namespace: calendar-hippo
