---
# Source: datadog/templates/install_info-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-hippo-datadog-installinfo
  namespace: calendar-hippo
  labels:
    helm.sh/chart: 'datadog-3.77.0'
    app.kubernetes.io/name: "agent-hippo-datadog"
    app.kubernetes.io/instance: "agent-hippo"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
  annotations:
    checksum/install_info: f403040e6025b96734be0a558887981234898c3cae7f36887aa7f3f4eefe5ea4
data:
  install_info: |
    ---
    install_method:
      tool: helm
      tool_version: Helm
      installer_version: datadog-3.77.0
