---
# Source: datadog/templates/kpi-telemetry-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-hippo-datadog-kpi-telemetry-configmap
  namespace: calendar-hippo
  labels:
    helm.sh/chart: 'datadog-3.77.0'
    app.kubernetes.io/name: "agent-hippo-datadog"
    app.kubernetes.io/instance: "agent-hippo"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
data:
  install_type: k8s_manual
  install_id: "77d63dd1-4742-46b7-b031-ebf1bc14c1bf"
  install_time: "1730451304"
