---
# Source: datadog/templates/secret-cluster-agent-token.yaml
apiVersion: v1
kind: Secret
metadata:
  name: agent-hippo-datadog-cluster-agent
  namespace: calendar-hippo
  labels:
    helm.sh/chart: 'datadog-3.77.0'
    app.kubernetes.io/name: "agent-hippo-datadog"
    app.kubernetes.io/instance: "agent-hippo"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
type: Opaque
data:
  token: "T3loRGdyU3dzOWZDSTRGbTZuT2JnM1ZyZEZUN3Q3bFE="
